apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - configmap.yaml
labels:
  - pairs:
      env: dev
images:
  - name: pos-app
    newName: ghcr.io/thant7intun/pos-app
    newTag: 4-10a7a1e
replicas:
  - name: pos-app
    count: 1
