apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
labels:
  - pairs:
      env: dev
images:
  - name: payment-service
    newName: ghcr.io/zawthanoo/payment-service
    newTag: local
replicas:
  - name: payment-service
    count: 1
configMapGenerator:
  - name: payment-service-config
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
