apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop

resources:
  - ../inventory-service/overlays/uat
  - ../order-service/overlays/uat
  - ../payment-service/overlays/uat
  - ../pos-app/overlays/uat
